# Generated by Django 4.2.1 on 2023-10-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0003_acessomedico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessomedico',
            name='token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
